name: cdi-data-acquisition

channels:
  - conda-forge
  - bioconda

dependencies:
  # Metadata acquisition
  - entrez-direct
  - pysradb

  # Download system
  - sra-tools
  - wget
  - curl

  # Validation and inventory
  - seqkit
  - csvtk

  # Command-line processing
  - jq
  - parallel
  - pigz

  # General utilities
  - python