<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Download System – CDI Data Acquisition System</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-data-validation-system.html" rel="next">
<link href="./04-metadata-acquisition.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-231ef2f9d4ce3268f31ef752336c15d2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="mermaid-theme" content="forest">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="assets/css/cdi.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-metadata-acquisition.html">Acquisition Systems</a></li><li class="breadcrumb-item"><a href="./05-data-download-system.html"><span class="chapter-title">Data Download System</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">CDI Data Acquisition System</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">index.html</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface-and-overview.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface and Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-public-data-landscape.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Public Data Landscape</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-study-discovery.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Study Discovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-accession-systems.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Accession Systems</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Acquisition Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-metadata-acquisition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Metadata Acquisition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data-download-system.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Data Download System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-data-validation-system.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Validation System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-cloud-storage-and-transfer-system.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cloud Storage and Transfer System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-reference-dataset-assembly-system.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reference Dataset Assembly</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Case Study</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-end-to-end-case-study.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">End-to-End Case Study</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./999-appendix.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Acquisition References</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./999-references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#why-a-data-download-system-matters" id="toc-why-a-data-download-system-matters" class="nav-link" data-scroll-target="#why-a-data-download-system-matters">Why a Data Download System Matters</a></li>
  <li><a href="#data-download-system-architecture" id="toc-data-download-system-architecture" class="nav-link" data-scroll-target="#data-download-system-architecture">Data Download System Architecture</a></li>
  <li><a href="#environment-reuse" id="toc-environment-reuse" class="nav-link" data-scroll-target="#environment-reuse">Environment Reuse</a></li>
  <li><a href="#cdi-data-acquisition-environment" id="toc-cdi-data-acquisition-environment" class="nav-link" data-scroll-target="#cdi-data-acquisition-environment">CDI Data Acquisition Environment</a></li>
  <li><a href="#environment-verification" id="toc-environment-verification" class="nav-link" data-scroll-target="#environment-verification">Environment Verification</a></li>
  <li><a href="#common-sources-of-downloadable-data" id="toc-common-sources-of-downloadable-data" class="nav-link" data-scroll-target="#common-sources-of-downloadable-data">Common Sources of Downloadable Data</a></li>
  <li><a href="#common-download-formats" id="toc-common-download-formats" class="nav-link" data-scroll-target="#common-download-formats">Common Download Formats</a></li>
  <li><a href="#metadata-assets-as-inputs" id="toc-metadata-assets-as-inputs" class="nav-link" data-scroll-target="#metadata-assets-as-inputs">Metadata Assets as Inputs</a></li>
  <li><a href="#download-manifest" id="toc-download-manifest" class="nav-link" data-scroll-target="#download-manifest">Download Manifest</a></li>
  <li><a href="#download-strategy" id="toc-download-strategy" class="nav-link" data-scroll-target="#download-strategy">Download Strategy</a></li>
  <li><a href="#download-tools" id="toc-download-tools" class="nav-link" data-scroll-target="#download-tools">Download Tools</a>
  <ul class="collapse">
  <li><a href="#sra-toolkit" id="toc-sra-toolkit" class="nav-link" data-scroll-target="#sra-toolkit">SRA Toolkit</a></li>
  <li><a href="#ftp-and-https-utilities" id="toc-ftp-and-https-utilities" class="nav-link" data-scroll-target="#ftp-and-https-utilities">FTP and HTTPS Utilities</a></li>
  <li><a href="#cloud-based-access" id="toc-cloud-based-access" class="nav-link" data-scroll-target="#cloud-based-access">Cloud-Based Access</a></li>
  </ul></li>
  <li><a href="#installing-sra-toolkit" id="toc-installing-sra-toolkit" class="nav-link" data-scroll-target="#installing-sra-toolkit">Installing SRA Toolkit</a></li>
  <li><a href="#checking-download-utilities" id="toc-checking-download-utilities" class="nav-link" data-scroll-target="#checking-download-utilities">Checking Download Utilities</a></li>
  <li><a href="#recommended-directory-structure" id="toc-recommended-directory-structure" class="nav-link" data-scroll-target="#recommended-directory-structure">Recommended Directory Structure</a></li>
  <li><a href="#building-a-download-manifest" id="toc-building-a-download-manifest" class="nav-link" data-scroll-target="#building-a-download-manifest">Building a Download Manifest</a></li>
  <li><a href="#system-scripts" id="toc-system-scripts" class="nav-link" data-scroll-target="#system-scripts">System Scripts</a></li>
  <li><a href="#testing-and-verifying-the-download-system" id="toc-testing-and-verifying-the-download-system" class="nav-link" data-scroll-target="#testing-and-verifying-the-download-system">Testing and Verifying the Download System</a>
  <ul class="collapse">
  <li><a href="#verification-results" id="toc-verification-results" class="nav-link" data-scroll-target="#verification-results">Verification Results</a></li>
  </ul></li>
  <li><a href="#repository-selection-strategy" id="toc-repository-selection-strategy" class="nav-link" data-scroll-target="#repository-selection-strategy">Repository Selection Strategy</a></li>
  <li><a href="#download-workflow-1-ena-direct-fastq-download" id="toc-download-workflow-1-ena-direct-fastq-download" class="nav-link" data-scroll-target="#download-workflow-1-ena-direct-fastq-download">Download Workflow 1: ENA Direct FASTQ Download</a></li>
  <li><a href="#download-workflow-2-ncbi-sra-retrieval" id="toc-download-workflow-2-ncbi-sra-retrieval" class="nav-link" data-scroll-target="#download-workflow-2-ncbi-sra-retrieval">Download Workflow 2: NCBI SRA Retrieval</a></li>
  <li><a href="#checksum-verification" id="toc-checksum-verification" class="nav-link" data-scroll-target="#checksum-verification">Checksum Verification</a></li>
  <li><a href="#fastq-inventory-generation" id="toc-fastq-inventory-generation" class="nav-link" data-scroll-target="#fastq-inventory-generation">FASTQ Inventory Generation</a></li>
  <li><a href="#end-to-end-download-example" id="toc-end-to-end-download-example" class="nav-link" data-scroll-target="#end-to-end-download-example">End-to-End Download Example</a></li>
  <li><a href="#common-challenges" id="toc-common-challenges" class="nav-link" data-scroll-target="#common-challenges">Common Challenges</a></li>
  <li><a href="#reproducible-download-workflows" id="toc-reproducible-download-workflows" class="nav-link" data-scroll-target="#reproducible-download-workflows">Reproducible Download Workflows</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#system-validation" id="toc-system-validation" class="nav-link" data-scroll-target="#system-validation">System Validation</a></li>
  </ul></li>
  <li><a href="#looking-ahead" id="toc-looking-ahead" class="nav-link" data-scroll-target="#looking-ahead">Looking Ahead</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-metadata-acquisition.html">Acquisition Systems</a></li><li class="breadcrumb-item"><a href="./05-data-download-system.html"><span class="chapter-title">Data Download System</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Data Download System</span></h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Jun 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cdi-message">
<ul>
<li><strong>ID:</strong> DAS-005</li>
<li><strong>Type:</strong> Acquisition Systems</li>
<li><strong>Audience:</strong> Omics Data Scientists, Bioinformaticians, and Research Teams</li>
<li><strong>Theme:</strong> From Download Manifests to Verified FASTQ Assets</li>
</ul>
</div>
<p>Once studies have been identified, accession systems understood, and metadata evaluated, the next step is acquiring the sequencing data.</p>
<p>Data download transforms study selection and metadata assets into locally accessible sequencing files that can be validated, organized, transferred, and assembled into downstream reference datasets. A reproducible acquisition workflow requires more than simply downloading files. Researchers must understand where files reside, how they are accessed, how downloads can be resumed, and how file integrity can be verified.</p>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li>Select appropriate repositories for sequencing data download.</li>
<li>Reuse the CDI data acquisition Conda environment.</li>
<li>Install and verify SRA Toolkit commands.</li>
<li>Build download manifests from metadata assets.</li>
<li>Retrieve sequencing files through ENA and NCBI workflows.</li>
<li>Organize downloaded files into a reproducible project structure.</li>
<li>Verify file presence, file size, checksums, and sample counts.</li>
<li>Generate FASTQ inventories for downstream validation.</li>
</ul>
</section>
<section id="why-a-data-download-system-matters" class="level2">
<h2 class="anchored" data-anchor-id="why-a-data-download-system-matters">Why a Data Download System Matters</h2>
<p>Metadata acquisition tells us what data exist.</p>
<p>The Data Download System retrieves the actual sequencing files required for downstream analysis.</p>
<pre class="text"><code>Metadata Assets
      ↓
Download Manifest
      ↓
Repository Selection
      ↓
Download Execution
      ↓
Integrity Verification
      ↓
FASTQ Inventory
      ↓
Data Validation System</code></pre>
<p>The quality of downstream analyses depends on the quality and completeness of acquired data. A successful download workflow should ensure that:</p>
<ul>
<li>The correct files are retrieved.</li>
<li>Files are complete.</li>
<li>Downloads are reproducible.</li>
<li>Data provenance is preserved.</li>
<li>Acquisition steps can be repeated when necessary.</li>
</ul>
</section>
<section id="data-download-system-architecture" class="level2">
<h2 class="anchored" data-anchor-id="data-download-system-architecture">Data Download System Architecture</h2>
<div class="cell" data-layout-align="default">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>A[Metadata Assets]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>--&gt; B[Download Manifest]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>B --&gt; C[Repository Selection]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>C --&gt; D[Download Execution]</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>D --&gt; E[Integrity Verification]</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>E --&gt; F[FASTQ Inventory]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>F --&gt; G[Data Validation System]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Metadata Assets]
--&gt; B[Download Manifest]

B --&gt; C[Repository Selection]

C --&gt; D[Download Execution]

D --&gt; E[Integrity Verification]

E --&gt; F[FASTQ Inventory]

F --&gt; G[Data Validation System]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The Data Download System begins with metadata assets generated in Chapter 04 and ends with a documented inventory of downloaded files.</p>
</section>
<section id="environment-reuse" class="level2">
<h2 class="anchored" data-anchor-id="environment-reuse">Environment Reuse</h2>
<p>The CDI Data Acquisition System uses a single Conda environment throughout the workflow.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> activate cdi-data-acquisition</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This avoids unnecessary environment switching and ensures that metadata acquisition, data download, validation, and dataset assembly operate within a consistent software environment.</p>
</section>
<section id="cdi-data-acquisition-environment" class="level2">
<h2 class="anchored" data-anchor-id="cdi-data-acquisition-environment">CDI Data Acquisition Environment</h2>
<p>The environment used throughout this book is defined as:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">name</span><span class="kw">:</span><span class="at"> cdi-data-acquisition</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">channels</span><span class="kw">:</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> conda-forge</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> bioconda</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dependencies</span><span class="kw">:</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> entrez-direct</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> pysradb</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> sra-tools</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> wget</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> curl</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> seqkit</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> csvtk</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> jq</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> parallel</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> pigz</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="kw">-</span><span class="at"> python</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<hr>
</section>
<section id="environment-verification" class="level2">
<h2 class="anchored" data-anchor-id="environment-verification">Environment Verification</h2>
<p>Verify the key tools required by the Data Download System.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> <span class="at">--version</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="ex">prefetch</span> <span class="at">--version</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="ex">fasterq-dump</span> <span class="at">--version</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="ex">vdb-validate</span> <span class="at">--version</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="ex">pysradb</span> <span class="at">--help</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="ex">seqkit</span> version</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="ex">csvtk</span> version</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="ex">jq</span> <span class="at">--version</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="ex">parallel</span> <span class="at">--version</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span> esearch</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Successful execution confirms that the shared CDI data acquisition environment is ready for metadata acquisition, data download, and data validation workflows.</p>
</section>
<section id="common-sources-of-downloadable-data" class="level2">
<h2 class="anchored" data-anchor-id="common-sources-of-downloadable-data">Common Sources of Downloadable Data</h2>
<p>Public repositories provide access to a variety of downloadable file types.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 25%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Repository</th>
<th>Typical Data</th>
<th>Common Role in This System</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SRA</td>
<td>Raw sequencing reads</td>
<td>Run accession source and SRA Toolkit download</td>
</tr>
<tr class="even">
<td>ENA</td>
<td>Raw sequencing reads and FASTQ URLs</td>
<td>Direct FASTQ retrieval and checksum validation</td>
</tr>
<tr class="odd">
<td>GEO</td>
<td>Processed and supplementary data</td>
<td>Study-level context and supplementary files</td>
</tr>
<tr class="even">
<td>MGnify</td>
<td>Processed microbiome outputs</td>
<td>Processed microbiome reference outputs</td>
</tr>
<tr class="odd">
<td>GWAS Catalog</td>
<td>Summary statistics and study information</td>
<td>Association study discovery and summary statistics</td>
</tr>
</tbody>
</table>
<p>For large public sequencing datasets, the two most important download sources are usually <strong>ENA</strong> and <strong>NCBI SRA</strong>.</p>
</section>
<section id="common-download-formats" class="level2">
<h2 class="anchored" data-anchor-id="common-download-formats">Common Download Formats</h2>
<p>Researchers frequently encounter:</p>
<ul>
<li>FASTQ</li>
<li>FASTA</li>
<li>BAM</li>
<li>CRAM</li>
<li>TSV</li>
<li>CSV</li>
<li>Metadata spreadsheets</li>
</ul>
<p>For raw sequencing acquisition, the most common target output is FASTQ. In microbiome, RNA-seq, metagenomics, and many other NGS workflows, FASTQ files serve as the starting point for downstream quality control and analysis.</p>
</section>
<section id="metadata-assets-as-inputs" class="level2">
<h2 class="anchored" data-anchor-id="metadata-assets-as-inputs">Metadata Assets as Inputs</h2>
<p>The Data Download System consumes metadata assets generated during metadata acquisition.</p>
<pre class="text"><code>data/
└── metadata/
    ├── runinfo-prjna477349.csv
    ├── ena-prjna477349.tsv
    └── srr-accessions.txt</code></pre>
<p>These files provide accession identifiers, sample-level metadata, and potential download locations required for data retrieval.</p>
<p>The most important handoff from Chapter 04 is the run accession list:</p>
<pre class="text"><code>SRR accession list
      ↓
Download manifest
      ↓
FASTQ retrieval</code></pre>
</section>
<section id="download-manifest" class="level2">
<h2 class="anchored" data-anchor-id="download-manifest">Download Manifest</h2>
<p>A download manifest represents the authoritative list of files or accessions to retrieve.</p>
<p>A simple accession-only manifest may look like this:</p>
<pre class="text"><code>SRR1234567
SRR1234568
SRR1234569</code></pre>
<p>A richer manifest may include repository links and checksums:</p>
<pre class="text"><code>run_accession    fastq_ftp                         fastq_md5
SRR1234567       ftp.sra.ebi.ac.uk/.../file_1.gz   abc123...
SRR1234568       ftp.sra.ebi.ac.uk/.../file_1.gz   def456...</code></pre>
<p>Recommended output location:</p>
<pre class="text"><code>data/
└── manifests/
    └── download-manifest.tsv</code></pre>
<p>The manifest becomes the system contract: it defines what should be downloaded, from where, and how completeness will later be checked.</p>
</section>
<section id="download-strategy" class="level2">
<h2 class="anchored" data-anchor-id="download-strategy">Download Strategy</h2>
<p>The CDI Data Acquisition System uses a staged download strategy that validates repository workflows before initiating large-scale data retrieval.</p>
<pre class="text"><code>Build Manifest
      ↓
Create Test Manifest
      ↓
Validate Repository Workflows
      ├── ENA
      └── NCBI/SRA
      ↓
Production Download</code></pre>
<p>This approach reduces risk by ensuring that:</p>
<ul>
<li>Metadata have been translated correctly into download manifests.</li>
<li>Repository access is functioning as expected.</li>
<li>Download scripts operate correctly.</li>
<li>Retrieved files can be validated before large-scale acquisition.</li>
<li>Bandwidth and storage resources are used efficiently.</li>
</ul>
<p>The test manifest generated from the full download manifest serves as a representative subset for repository validation.</p>
<pre class="text"><code>download-manifest.tsv
        ↓
test-manifest.tsv
        ↓
Repository Validation
        ↓
Production Download</code></pre>
<p>Successful test downloads provide confidence that the acquisition workflow is functioning correctly before scaling to the complete dataset.</p>
<p>Only after successful repository validation should production downloads be initiated.</p>
</section>
<section id="download-tools" class="level2">
<h2 class="anchored" data-anchor-id="download-tools">Download Tools</h2>
<p>Several tools are commonly used to retrieve public omics datasets.</p>
<section id="sra-toolkit" class="level3">
<h3 class="anchored" data-anchor-id="sra-toolkit">SRA Toolkit</h3>
<p>The SRA Toolkit is commonly used for retrieving sequencing data from the NCBI Sequence Read Archive.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tool</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>prefetch</code></td>
<td>Download SRA files</td>
</tr>
<tr class="even">
<td><code>fasterq-dump</code></td>
<td>Convert SRA files to FASTQ</td>
</tr>
<tr class="odd">
<td><code>vdb-validate</code></td>
<td>Validate downloaded SRA files</td>
</tr>
</tbody>
</table>
</section>
<section id="ftp-and-https-utilities" class="level3">
<h3 class="anchored" data-anchor-id="ftp-and-https-utilities">FTP and HTTPS Utilities</h3>
<p>ENA and other repositories often expose direct file links that can be retrieved with common command-line tools.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tool</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>wget</code></td>
<td>Download files from HTTP, HTTPS, or FTP links</td>
</tr>
<tr class="even">
<td><code>curl</code></td>
<td>Retrieve files and web resources</td>
</tr>
<tr class="odd">
<td><code>md5sum</code></td>
<td>Verify MD5 checksums on Linux</td>
</tr>
<tr class="even">
<td><code>md5</code></td>
<td>Verify MD5 checksums on macOS</td>
</tr>
</tbody>
</table>
</section>
<section id="cloud-based-access" class="level3">
<h3 class="anchored" data-anchor-id="cloud-based-access">Cloud-Based Access</h3>
<p>Some repositories also provide access through cloud infrastructure and object storage systems. Cloud transfer workflows are introduced later in the book, after local download and validation concepts are established.</p>
</section>
</section>
<section id="installing-sra-toolkit" class="level2">
<h2 class="anchored" data-anchor-id="installing-sra-toolkit">Installing SRA Toolkit</h2>
<p>Activate the shared CDI data acquisition environment:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> activate cdi-data-acquisition</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Install SRA Toolkit:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> install <span class="at">-c</span> bioconda sra-tools</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Verify installation:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">prefetch</span> <span class="at">--version</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="ex">fasterq-dump</span> <span class="at">--version</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="ex">vdb-validate</span> <span class="at">--version</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If the commands return version information, the toolkit is available in the active environment.</p>
</section>
<section id="checking-download-utilities" class="level2">
<h2 class="anchored" data-anchor-id="checking-download-utilities">Checking Download Utilities</h2>
<p>Many systems already include <code>curl</code>. Some may require <code>wget</code> installation.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">--version</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wget</span> <span class="at">--version</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If <code>wget</code> is missing, install it in the same environment:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> install <span class="at">-c</span> conda-forge wget</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>For checksum verification, Linux commonly uses:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">md5sum</span> <span class="at">--version</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>On macOS, use:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="ex">md5</span> <span class="at">--version</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The exact checksum command can differ by operating system, but the purpose is the same: confirm that downloaded files match the expected repository checksums.</p>
</section>
<section id="recommended-directory-structure" class="level2">
<h2 class="anchored" data-anchor-id="recommended-directory-structure">Recommended Directory Structure</h2>
<p>Downloaded files should be organized systematically.</p>
<p>Recommended structure:</p>
<pre class="text"><code>data/
├── metadata/
│   ├── runinfo-prjna477349.csv
│   ├── ena-prjna477349.tsv
│   └── srr-accessions.txt
│
├── manifests/
│   └── download-manifest.tsv
│
├── raw/
│   ├── sra/
│   └── fastq/
│
├── logs/
│   ├── download-ena.log
│   ├── download-ncbi.log
│   └── checksum.log
│
└── inventory/
    └── fastq-inventory.tsv</code></pre>
<p>A consistent structure improves reproducibility, simplifies validation, and provides a clear handoff between chapters.</p>
<p>Create the directories:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> data/manifests</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> data/raw/sra</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> data/raw/fastq</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> data/logs</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> data/inventory</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="building-a-download-manifest" class="level2">
<h2 class="anchored" data-anchor-id="building-a-download-manifest">Building a Download Manifest</h2>
<p>A minimal accession manifest can be copied from the Chapter 04 output:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cp</span> data/metadata/srr-accessions.txt data/manifests/download-manifest.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Preview the manifest:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> data/manifests/download-manifest.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Count accessions:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wc</span> <span class="at">-l</span> data/manifests/download-manifest.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The expected count becomes one of the first validation checks after download.</p>
</section>
<section id="system-scripts" class="level2">
<h2 class="anchored" data-anchor-id="system-scripts">System Scripts</h2>
<p>The CDI Data Download System is implemented through a set of reusable Bash scripts.</p>
<pre class="text"><code>scripts/bash/
├── 05a-build-download-manifest.sh
│   └── Create production and test manifests
│
├── 05b-download-ena-fastq.sh
│   └── Download FASTQ files from ENA
│
├── 05c-download-ncbi-sra.sh
│   └── Download and convert SRA accessions
│
├── 05d-verify-downloads.sh
│   └── Verify downloaded FASTQ assets
│
└── 05e-build-fastq-inventory.sh
    └── Generate FASTQ inventory reports</code></pre>
<p>These scripts operate on the directory structure and manifest created in the previous sections and provide a reproducible implementation of the Data Download System.</p>
<p>Before executing the full workflow, it is good practice to validate the environment, directory structure, and download process using a single accession. The following section demonstrates this verification step before scaling to larger manifests and automated script execution.</p>
</section>
<section id="testing-and-verifying-the-download-system" class="level2">
<h2 class="anchored" data-anchor-id="testing-and-verifying-the-download-system">Testing and Verifying the Download System</h2>
<p>Before downloading an entire dataset, it is good practice to validate the workflow using a single accession from the download manifest.</p>
<p>Preview the first accession:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> <span class="at">-n</span> 1 data/manifests/download-manifest.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>SRR7450741</code></pre>
<p>Download the accession using SRA Toolkit:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="ex">prefetch</span> SRR7450741 <span class="dt">\</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">--output-directory</span> data/raw/sra</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Successful execution created:</p>
<pre class="text"><code>data/raw/sra/
└── SRR7450741/
    └── SRR7450741.sra</code></pre>
<p>Verify the downloaded file:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find</span> data/raw/sra <span class="at">-type</span> f</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>data/raw/sra/SRR7450741/SRR7450741.sra</code></pre>
<p>Convert the SRA file to FASTQ:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="ex">fasterq-dump</span> <span class="dt">\</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  data/raw/sra/SRR7450741/SRR7450741.sra <span class="dt">\</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">--outdir</span> data/raw/fastq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>spots read      : 79,065
reads read      : 158,130
reads written   : 158,130</code></pre>
<p>Inspect the generated FASTQ files:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-lh</span> data/raw/fastq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>total 115344
-rw-r--r--@ 1 tmbmacbookair  staff    28M Jun 11 15:35 SRR7450741_1.fastq
-rw-r--r--@ 1 tmbmacbookair  staff    28M Jun 11 15:35 SRR7450741_2.fastq</code></pre>
<p>The presence of two FASTQ files indicates that this sequencing run is paired-end.</p>
<p>Perform a preliminary validation using SeqKit:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="ex">seqkit</span> stats data/raw/fastq/<span class="pp">*</span>.fastq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>file                               format  type  num_seqs     sum_len  min_len  avg_len  max_len
data/raw/fastq/SRR7450741_1.fastq  FASTQ   DNA     79,065  11,938,815      151      151      151
data/raw/fastq/SRR7450741_2.fastq  FASTQ   DNA     79,065  11,938,815      151      151      151</code></pre>
<section id="verification-results" class="level3">
<h3 class="anchored" data-anchor-id="verification-results">Verification Results</h3>
<p>This simple test confirms that:</p>
<ul>
<li>The download manifest is valid.</li>
<li>SRA Toolkit successfully retrieved the sequencing run.</li>
<li>FASTQ conversion completed without errors.</li>
<li>The run is paired-end, producing two FASTQ files.</li>
<li>Both FASTQ files contain the same number of reads (79,065).</li>
<li>Read counts are consistent with the reported number of sequencing spots.</li>
<li>Read length is uniform at 151 bp across both files.</li>
<li>SeqKit successfully parsed both FASTQ files.</li>
<li>No obvious truncation or corruption is detected.</li>
</ul>
<p>At this stage we have demonstrated:</p>
<pre class="text"><code>Metadata Assets
        ↓
Download Manifest
        ↓
SRA Download
        ↓
FASTQ Generation
        ↓
Basic Validation</code></pre>
<p>This preliminary verification provides confidence that the acquisition workflow is functioning correctly.</p>
<p>Rather than immediately downloading hundreds of sequencing runs, validating the workflow on a single accession helps confirm that repository access, directory structure, software installation, FASTQ conversion, and basic file inspection are all functioning as expected.</p>
<p>Once the workflow has been verified, the same approach can be scaled to the complete download manifest through the CDI Data Download System scripts.</p>
<p>The following sections describe two common strategies for large-scale data acquisition: direct FASTQ retrieval from ENA and SRA-based retrieval using the NCBI SRA Toolkit. Rather than executing individual commands manually, these workflows are implemented through the reusable Bash scripts introduced above.</p>
</section>
</section>
<section id="repository-selection-strategy" class="level2">
<h2 class="anchored" data-anchor-id="repository-selection-strategy">Repository Selection Strategy</h2>
<p>The recommended strategy is to use NCBI for study discovery and accession resolution, then use ENA for direct FASTQ download when suitable links and checksums are available.</p>
<pre class="text"><code>Study Discovery
      ↓
NCBI
      ↓
Metadata Acquisition
      ↓
ENA
      ↓
Download Planning
      ↓
Data Download</code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Scenario</th>
<th>Preferred Repository</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Metadata discovery</td>
<td>NCBI</td>
</tr>
<tr class="even">
<td>FASTQ download with direct URLs</td>
<td>ENA</td>
</tr>
<tr class="odd">
<td>Missing FASTQ URLs</td>
<td>NCBI SRA Toolkit</td>
</tr>
<tr class="even">
<td>Need SRA-native retrieval</td>
<td>NCBI SRA Toolkit</td>
</tr>
<tr class="odd">
<td>Controlled-access data</td>
<td>Repository-specific process</td>
</tr>
<tr class="even">
<td>Supplementary processed files</td>
<td>GEO, ENA, project archive, or journal supplement</td>
</tr>
</tbody>
</table>
<p>This strategy avoids treating all repositories as interchangeable. Each repository contributes differently to the acquisition system.</p>
</section>
<section id="download-workflow-1-ena-direct-fastq-download" class="level2">
<h2 class="anchored" data-anchor-id="download-workflow-1-ena-direct-fastq-download">Download Workflow 1: ENA Direct FASTQ Download</h2>
<p>ENA is often preferred when direct FASTQ links and MD5 checksums are available.</p>
<pre class="text"><code>ENA Metadata
      ↓
FASTQ URLs
      ↓
wget or curl
      ↓
FASTQ Files
      ↓
Checksum Verification</code></pre>
<p>The ENA metadata file may contain columns such as:</p>
<ul>
<li><code>run_accession</code></li>
<li><code>fastq_ftp</code></li>
<li><code>fastq_md5</code></li>
<li><code>fastq_bytes</code></li>
</ul>
<p>The exact column names should be inspected before writing download commands:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> <span class="at">-n</span> 1 data/metadata/ena-prjna477349.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The ENA download workflow is implemented by:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bash</span> scripts/bash/05b-download-ena-fastq.sh</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This script extracts FASTQ URLs from the ENA metadata file, writes them to:</p>
<pre class="text"><code>data/manifests/ena-fastq-urls.txt</code></pre>
<p>and downloads the files into:</p>
<pre class="text"><code>data/raw/fastq/</code></pre>
<p>Download logs are written to:</p>
<pre class="text"><code>data/logs/download-ena.log</code></pre>
<p>The script uses <code>wget --continue</code>, which allows interrupted downloads to resume when possible.</p>
</section>
<section id="download-workflow-2-ncbi-sra-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="download-workflow-2-ncbi-sra-retrieval">Download Workflow 2: NCBI SRA Retrieval</h2>
<p>When direct FASTQ links are unavailable, the SRA Toolkit workflow can be used.</p>
<pre class="text"><code>SRR Accessions
      ↓
prefetch
      ↓
SRA Files
      ↓
fasterq-dump
      ↓
FASTQ Files</code></pre>
<p>The NCBI SRA workflow is implemented by:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bash</span> scripts/bash/05c-download-ncbi-sra.sh</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>By default, this script uses the small test manifest:</p>
<pre class="text"><code>data/manifests/test-manifest.tsv</code></pre>
<p>This makes the workflow safe for testing and book development.</p>
<p>To run the workflow on the full dataset, provide the full manifest explicitly:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bash</span> scripts/bash/05c-download-ncbi-sra.sh <span class="dt">\</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  data/manifests/download-manifest.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The script performs three steps:</p>
<pre class="text"><code>Download SRA files
      ↓
Convert SRA to FASTQ
      ↓
Compress FASTQ files</code></pre>
<p>Outputs are written to:</p>
<pre class="text"><code>data/raw/sra/
data/raw/fastq/
data/logs/download-ncbi.log</code></pre>
<p>This test-first pattern prevents accidentally launching a full dataset download before the workflow has been validated.</p>
<p>For large datasets, compression can take time. Faster alternatives such as <code>pigz</code> can be used when parallel compression is required.</p>
<p>The previous single-accession test demonstrated that the download workflow is functioning correctly on a representative sequencing run. After scaling to the complete download manifest, additional checks should be performed to confirm file integrity and completeness before proceeding to downstream validation.</p>
<p>Common post-download checks include:</p>
<ul>
<li>Expected file counts</li>
<li>Checksum validation</li>
<li>Metadata consistency</li>
<li>Sample completeness</li>
</ul>
<p>The following section focuses on checksum verification, one of the most important safeguards against incomplete or corrupted downloads.</p>
</section>
<section id="checksum-verification" class="level2">
<h2 class="anchored" data-anchor-id="checksum-verification">Checksum Verification</h2>
<p>If ENA provides MD5 checksums, they should be used to verify that downloaded FASTQ files match the files distributed by the repository.</p>
<p>A checksum file may look like this:</p>
<pre class="text"><code>abc123...  SRR1234567_1.fastq.gz
def456...  SRR1234567_2.fastq.gz</code></pre>
<p>On Linux:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> data/raw/fastq</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">md5sum</span> <span class="at">-c</span> ../../manifests/ena-md5.txt <span class="kw">|</span> <span class="fu">tee</span> ../../logs/checksum.log</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> <span class="at">-</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>On macOS, checksum verification may require a slightly different command or installing GNU coreutils.</p>
<p>The important principle is that expected checksums from the repository should match the local downloaded files.</p>
</section>
<section id="fastq-inventory-generation" class="level2">
<h2 class="anchored" data-anchor-id="fastq-inventory-generation">FASTQ Inventory Generation</h2>
<p>A FASTQ inventory records the sequencing files acquired during the download process and provides a reproducible record of downloaded assets.</p>
<p>Recommended output:</p>
<pre class="text"><code>data/
└── inventory/
    └── fastq-inventory.tsv</code></pre>
<p>The inventory workflow is implemented through:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bash</span> scripts/bash/05e-build-fastq-inventory.sh</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This script scans the FASTQ directory and generates an inventory containing file names and file sizes.</p>
<p>Preview the inventory:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> data/inventory/fastq-inventory.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Count inventory records:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wc</span> <span class="at">-l</span> data/inventory/fastq-inventory.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Example output:</p>
<pre class="text"><code>file    size_bytes
data/raw/fastq/SRR7450741_1.fastq.gz    12123456
data/raw/fastq/SRR7450741_2.fastq.gz    12098765</code></pre>
<p>The inventory provides a concise summary of acquired sequencing assets and supports:</p>
<ul>
<li>FASTQ file counting</li>
<li>Storage estimation</li>
<li>Download completeness assessment</li>
<li>Sample tracking</li>
<li>Dataset auditing</li>
</ul>
<p>The expected number of FASTQ files, total storage requirements, and sample coverage can all be assessed from the inventory before formal validation begins.</p>
<p>The inventory becomes a key input to the Data Validation System introduced in Chapter 06.</p>
</section>
<section id="end-to-end-download-example" class="level2">
<h2 class="anchored" data-anchor-id="end-to-end-download-example">End-to-End Download Example</h2>
<p>Suppose a healthy reference microbiome project identifies 850 eligible samples.</p>
<p>The workflow proceeds as follows:</p>
<pre class="text"><code>850 Eligible Samples
        ↓
Metadata Acquisition
        ↓
Download Manifest
        ↓
Single-Accession Test
        ↓
Workflow Verification
        ↓
ENA or NCBI Download Workflow
        ↓
Download Verification
        ↓
FASTQ Inventory
        ↓
Data Validation System</code></pre>
<p>At this stage, the objective is not analysis. The objective is to acquire a complete and reproducible sequencing dataset suitable for downstream validation and reference dataset assembly.</p>
</section>
<section id="common-challenges" class="level2">
<h2 class="anchored" data-anchor-id="common-challenges">Common Challenges</h2>
<p>Researchers frequently encounter:</p>
<ul>
<li>Interrupted downloads</li>
<li>Missing files</li>
<li>Incomplete metadata</li>
<li>Repository-specific formats</li>
<li>Storage limitations</li>
<li>Slow transfer speeds</li>
<li>Inconsistent file naming</li>
<li>Paired-end files split across multiple URLs</li>
</ul>
<p>Planning for these challenges improves acquisition reliability.</p>
</section>
<section id="reproducible-download-workflows" class="level2">
<h2 class="anchored" data-anchor-id="reproducible-download-workflows">Reproducible Download Workflows</h2>
<p>Every download process should be documented.</p>
<p>Important records include:</p>
<ul>
<li>Repository source</li>
<li>Accessions used</li>
<li>Download date</li>
<li>Commands executed</li>
<li>File counts</li>
<li>Checksum results</li>
<li>Validation results</li>
</ul>
<p>The goal is not only to download files, but to make the download process auditable and repeatable.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>The Data Download System converts metadata assets into verified sequencing files.</p>
<pre class="text"><code>Metadata Assets
      ↓
Download Manifest
      ↓
Single-Accession Test
      ↓
Workflow Verification
      ↓
ENA or NCBI Download Workflow
      ↓
Download Verification
      ↓
FASTQ Inventory
      ↓
Data Validation System</code></pre>
<p>A reliable download system should answer five questions:</p>
<ul>
<li>What should be downloaded?</li>
<li>Where should it be downloaded from?</li>
<li>Has the download workflow been validated?</li>
<li>How can downloaded files be verified?</li>
<li>What inventory records the final acquired files?</li>
</ul>
<section id="system-validation" class="level3 cdi-message">
<h3 class="anchored" data-anchor-id="system-validation">System Validation</h3>
<p>The CDI Data Download System was validated using both ENA and NCBI acquisition workflows.</p>
<p>Validation included:</p>
<ul>
<li>Manifest generation (133 accessions)</li>
<li>Test manifest generation (3 accessions)</li>
<li>ENA direct FASTQ download</li>
<li>NCBI SRA download and FASTQ conversion</li>
<li>FASTQ verification using SeqKit</li>
<li>FASTQ inventory generation</li>
</ul>
<p>The validation workflow successfully generated sequencing files, verification reports, and inventory records from publicly available microbiome sequencing datasets.</p>
</section>
</section>
<section id="looking-ahead" class="level2">
<h2 class="anchored" data-anchor-id="looking-ahead">Looking Ahead</h2>
<p>After sequencing files have been downloaded, verified, and inventoried, the next challenge is determining whether the acquired dataset is complete, internally consistent, and suitable for downstream analysis.</p>
<p>In the next chapter, we implement the Data Validation System to evaluate file integrity, sample completeness, metadata consistency, and overall dataset readiness before reference dataset assembly and analysis.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-metadata-acquisition.html" class="pagination-link" aria-label="Metadata Acquisition">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Metadata Acquisition</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-data-validation-system.html" class="pagination-link" aria-label="Data Validation System">
        <span class="nav-page-text"><span class="chapter-title">Data Validation System</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>